### ISSUE TITLE
如何以json方式响应异常

### ISSUE THREAD

**Issue by glh1991** [beliefgp/egg-bizerror#1]
试了下, 输出的结果不是json.
config/errorcode.js
```js
module.exports = {
  'USER_NOT_FOUND': {
    status: 200,
    message: '用户不存在',
    code: 4000
  }
}
```
service/user.js
```js
async find(uid) {
    try {
      return await this.ctx.model.User.findOne({_id: uid});
    } catch (error) {
      this.ctx.throwBizError('USER_NOT_FOUND', error, { bizError: true })
    }
  }
```
app.js
```js
app.BizErrorHandler = class extends app.BizErrorHandler {
    json(ctx, error, config) {
      ctx.body = {
        code: config.code,
        msg: config.message,
      };
    }
  }
```
从mongo中查询一条记录,实际上该记录在mongo是不存在的, 抛出的CastError, catch后抛出业务异常, 期望响应的结果是以json的形式,形如handler中关于json方法的定义.实际结果如下:
 ```
<h2>用户不存在</h2>
<pre>
        code: 4000
    <pre>
```
是缺少什么配置亦或是还需要什么其他插件配合? node新手, 请赐教

**Comment by beliefgp** [comment]
这个应该是请求头的Accept，不是json类型吧

**Comment by scottming** [comment]
同遇到返回不是 json 的结果

**Comment by beliefgp** [comment]
@scottming  是  Request Headers 里的 Accept 头，不是 response 里的 conent-type

**Comment by beliefgp** [comment]
默认是根据 egg 自带的 api [ctx.acceptJSON](https://github.com/eggjs/egg/blob/master/app/extend/request.js#L135) 来判断的  
你重写下这个方法 [BizErrorHanlder.accepts](https://github.com/beliefgp/egg-bizerror/blob/master/lib/handler.js#L45) ，改为
```js
accepts(ctx) {
    if (ctx.acceptJSONP) {
      return 'jsonp';
    }
    return 'json';
  }
```
不是 jsonp 就全部当 json 吧

**Comment by beliefgp** [comment]
另外……
```js
// config/errorcode.js
module.exports = {
  'USER_NOT_EXIST': {
    status: 403,
    code: '10009'
    message: 'user not exist.'
  }
}
```
你直接配成这个就行了，不用重写 json 方法了，除非你们前端不是 `{ code, message }` 这种结构

**Comment by scottming** [comment]
好的，感谢。
